data<- read.table("./data/household_power_consumption.txt", header=TRUE, sep=";", col.names = c("date","time", "global_active_power", "global_reactive_power", "voltage", "global_intensity", "sub_metering_1", "sub_metering_2","sub_metering_3"))
data$date <- as.Date(data$date, format = "%d/%m/%Y")
newdata <- data[data$date >= "2007-02-01" & data$date <= "2007-02-02", ]
newdata$global_active_power<-as.numeric(paste(newdata$global_active_power))
newdata$voltage<-as.numeric(paste(newdata$voltage))
newdata$global_reactive_power<-as.numeric(paste(newdata$global_reactive_power))
newdata$sub_metering_1<-as.numeric(paste(newdata$sub_metering_1))
newdata$sub_metering_2<-as.numeric(paste(newdata$sub_metering_2))
newdata$sub_metering_3<-as.numeric(paste(newdata$sub_metering_3))
datetime <- paste(as.Date(newdata$date), newdata$time)
newdata$datetime <- as.POSIXct(datetime)
par(mfrow = c(2,2), mar = c(4,4,2,1), oma = c(0,0,2,0))
plot(newdata$datetime, newdata$global_active_power, type ="l", ylab = "Global Active Power", xlab = "" )
plot(newdata$datetime, newdata$voltage, type ="l", ylab = "Voltager", xlab = "datetime" )
plot(newdata$datetime, newdata$sub_metering_1, type = "l", ylab = "Global Active Power (kilowatts)", xlab ="")
lines(newdata$datetime,newdata$sub_metering_2, col = "red")
lines(newdata$datetime,newdata$sub_metering_3, col = "blue")
legend( "topright", col = c("black", "red", "blue"),lty = 1, lwd =2,bty ="n", legend = c("Sub_metering_1", "Sub_metering_2","Sub_metering_3"))
plot(newdata$datetime, newdata$global_reactive_power, type ="l", ylab = "Global_reactive_power", xlab = "datetime" )